import React from 'react';
import '../styles/main.css';

const Features = () => {
    return (
        <section id="features" className="features section-spacing">
            <h2 className="section-title">Key Features</h2>
            <div className="feature-cards">
                <div className="card animated-card">
                    <h3 className="feature-title">✨ AI-Powered Art</h3>
                    <p className="feature-description">Unleash your imagination with stunning visuals generated by OpenAI's DALL·E technology, bringing your stories to life with unparalleled creativity.</p>
                </div>
                <div className="card animated-card">
                    <h3 className="feature-title">🎭 Scene Splitting</h3>
                    <p className="feature-description">Effortlessly transform narratives into structured scenes using cutting-edge NLP for a seamless storytelling experience.</p>
                </div>
                <div className="card animated-card">
                    <h3 className="feature-title">📚 Modern Layouts</h3>
                    <p className="feature-description">Experience visually captivating comic book designs with expertly crafted grid layouts for a professional finish.</p>
                </div>
            </div>
        </section>
    );
};

export default Features;
